"""P2-STORAGE: Initial database schema for SQLite persistence

Revision ID: afd659fda61b
Revises: 
Create Date: 2026-02-02 19:38:25.419710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd659fda61b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_domain'), 'references', ['domain'], unique=False)
    op.create_index(op.f('ix_references_source_type'), 'references', ['source_type'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('folder', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('리드문', sa.Text(), nullable=False),
    sa.Column('정의', sa.Text(), nullable=False),
    sa.Column('키워드', sa.JSON(), nullable=False),
    sa.Column('해시태그', sa.String(), nullable=False),
    sa.Column('암기', sa.Text(), nullable=False),
    sa.Column('completion_리드문', sa.Boolean(), nullable=False),
    sa.Column('completion_정의', sa.Boolean(), nullable=False),
    sa.Column('completion_키워드', sa.Boolean(), nullable=False),
    sa.Column('completion_해시태그', sa.Boolean(), nullable=False),
    sa.Column('completion_암기', sa.Boolean(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('last_validated', sa.DateTime(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_domain'), 'topics', ['domain'], unique=False)
    op.create_index(op.f('ix_topics_file_path'), 'topics', ['file_path'], unique=False)
    op.create_table('validation_tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('topic_ids', sa.String(), nullable=False),
    sa.Column('domain_filter', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_content', sa.Text(), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('reference_sources', sa.JSON(), nullable=False),
    sa.Column('estimated_effort', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_priority'), 'proposals', ['priority'], unique=False)
    op.create_index(op.f('ix_proposals_topic_id'), 'proposals', ['topic_id'], unique=False)
    op.create_table('validations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('field_completeness_score', sa.Float(), nullable=False),
    sa.Column('content_accuracy_score', sa.Float(), nullable=False),
    sa.Column('reference_coverage_score', sa.Float(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('matched_references', sa.JSON(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validations_task_id'), 'validations', ['task_id'], unique=False)
    op.create_index(op.f('ix_validations_topic_id'), 'validations', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validations_topic_id'), table_name='validations')
    op.drop_index(op.f('ix_validations_task_id'), table_name='validations')
    op.drop_table('validations')
    op.drop_index(op.f('ix_proposals_topic_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_priority'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('validation_tasks')
    op.drop_index(op.f('ix_topics_file_path'), table_name='topics')
    op.drop_index(op.f('ix_topics_domain'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_references_source_type'), table_name='references')
    op.drop_index(op.f('ix_references_domain'), table_name='references')
    op.drop_table('references')
    # ### end Alembic commands ###
